version: '3.8'
services:
  xvm:
    build: .
    image: xvm-bvm:latest
    volumes:
      - ./rootdir:/rootdir
      - ./data:/data
    restart: always
    ports:
      - "8545:8545"
      - "8679:8679"